RealisticVision:
  inference_config: "configs/inference/inference-v2.yaml"
  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors" 
  #"models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors" "models/DreamBooth_LoRA/realisticVisionV51_v20Novae.safetensors"   
  lora_model_path: ""

  seed:           [13100322578370451493, 14752961627088720670, 9329399085567825781, 16987697414827649302]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "realistic highly detailed photo of 25 y.o woman extremely sexy naked, full body, standing, posing, blue eyes, body, high detailed skin, caucasian, skin pores, coastline, overcast weather, wind, waves, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"

  n_prompt:
    - "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"

